export interface RegisterModel {
          UserID:number,
          FullName :string,
          UserName :string,
          Bio :string,
          EmailId :string,
          Password :string,
          MobileNumber : number,
          PhotographLink :string,
          ResumeLink :string,
          WorkStatus :boolean,
          CurrentSalary : number,
          ExpectedSalary :number,
          CurrentLocation :string,
          PreferredLocation :string,
          CompanyName :string,
          RecruiterDescription :string,
          Role :string,
  }